(async function(){
 const $=s=>document.querySelector(s),esc=KasoliUI.escape;let products=[],editing=null,files=[],existingImages=[],deleteId=null,search="";
 if(!KasoliData.configured()){$("#authConfigured").hidden=true;$("#authNotConfigured").hidden=false;return}
 const allowed=email=>KASOLI_CONFIG.adminEmails.map(x=>x.toLowerCase()).includes((email||"").toLowerCase());
 async function enter(session){if(!session||!allowed(session.user.email)){if(session)await KasoliData.signOut();return}$("#authScreen").hidden=true;$("#adminApp").hidden=false;await load()}
 const initial=await KasoliData.session();if(initial)await enter(initial);
 $("#loginForm").addEventListener("submit",async e=>{e.preventDefault();const email=$("#loginEmail").value.trim();const error=$("#loginError"),btn=e.submitter;error.textContent="";if(!email||!/^\S+@\S+\.\S+$/.test(email)){error.textContent="Escribe un correo válido.";$("#loginEmail").focus();return}if(!allowed(email)){error.textContent="Este correo no está autorizado para administrar KASOLI.";return}btn.disabled=true;btn.textContent="Enviando…";try{const{error:authError}=await KasoliData.signIn(email);if(authError)throw authError;error.style.color="var(--success)";error.textContent="Revisa tu correo y abre el enlace de acceso."}catch(err){error.textContent=err.message||"No fue posible enviar el enlace."}finally{btn.disabled=false;btn.textContent="Enviar enlace de acceso"}});
 async function load(){try{products=await KasoliData.listAllProducts();render()}catch(e){KasoliUI.toast("No pudimos cargar los productos.")}}
 function filtered(){const q=search.toLocaleLowerCase("es");return products.filter(p=>!q||[p.name,p.category,p.material].join(" ").toLocaleLowerCase("es").includes(q))}
 function render(){const rows=filtered();$("#adminCount").textContent=`${products.length} en total`;$("#adminProducts").innerHTML=rows.map(p=>`<article class="admin-product"><img src="${esc(p.images?.[0]||"")}" alt=""><div><strong>${esc(p.name)}</strong><small>${esc(p.category)} · ${p.active?"Visible":"Oculto"}</small></div><div class="row-actions"><button type="button" data-edit="${esc(p.id)}">Editar</button><button class="delete" type="button" data-delete="${esc(p.id)}">Eliminar</button></div></article>`).join("");$("#adminEmpty").hidden=rows.length>0}
 function resetForm(){editing=null;files=[];existingImages=[];$("#productForm").reset();$("#active").checked=true;$("#productId").value="";$("#editorTitle").textContent="Nuevo producto";$("#saveProduct").textContent="Publicar producto";$("#formError").textContent="";renderUploads()}
 function edit(id){const p=products.find(x=>String(x.id)===String(id));if(!p)return;editing=p;files=[];existingImages=[...(p.images||[])];for(const key of ["name","category","collection","description","material","badge"]){$("#"+key).value=p[key]||""}$("#price").value=p.price||"";$("#sizes").value=(p.sizes||[]).join(", ");$("#colors").value=(p.colors||[]).join(", ");$("#active").checked=p.active!==false;$("#productId").value=p.id;$("#editorTitle").textContent="Editar producto";$("#saveProduct").textContent="Guardar cambios";renderUploads();$("#editor").scrollIntoView({behavior:"smooth",block:"start"});$("#name").focus()}
 function renderUploads(){const remote=existingImages.map((src,i)=>`<div class="upload-preview"><img src="${esc(src)}" alt="Foto guardada"><button type="button" data-remove-existing="${i}" aria-label="Quitar foto">×</button></div>`);const local=files.map((f,i)=>`<div class="upload-preview"><img src="${URL.createObjectURL(f)}" alt="Foto nueva"><button type="button" data-remove-file="${i}" aria-label="Quitar foto">×</button></div>`);$("#uploadList").innerHTML=[...remote,...local].join("")}
 function validate(){document.querySelectorAll("[data-error]").forEach(x=>x.textContent="");let first=null;for(const id of ["name","description"]){const input=$("#"+id);if(!input.value.trim()){const error=$(`[data-error='${id}']`);error.textContent="Este campo es obligatorio.";input.setAttribute("aria-invalid","true");if(!first)first=input}else input.removeAttribute("aria-invalid")}if(!existingImages.length&&!files.length){$("#uploadError").textContent="Agrega al menos una fotografía.";first=first||$("#images")}else $("#uploadError").textContent="";first?.focus();return !first}
 $("#images").addEventListener("change",e=>{const incoming=[...e.target.files];$("#uploadError").textContent="";for(const f of incoming){if(!["image/jpeg","image/png","image/webp"].includes(f.type)){$("#uploadError").textContent=`${f.name}: formato no admitido.`;continue}if(f.size>5*1024*1024){$("#uploadError").textContent=`${f.name}: supera 5 MB.`;continue}if(existingImages.length+files.length<4)files.push(f)}e.target.value="";renderUploads()});
 $("#uploadZone").addEventListener("keydown",e=>{if(e.key==="Enter"||e.key===" "){e.preventDefault();$("#images").click()}});
 $("#productForm").addEventListener("submit",async e=>{e.preventDefault();if(!validate())return;const btn=e.submitter,wasEditing=Boolean(editing);btn.disabled=true;btn.textContent="Publicando…";$("#formError").textContent="";try{const uploaded=[];for(const f of files)uploaded.push(await KasoliData.uploadImage(f));const id=editing?.id||crypto.randomUUID();const value={id,name:$("#name").value.trim(),category:$("#category").value,collection:$("#collection").value.trim(),description:$("#description").value.trim(),material:$("#material").value.trim(),price:$("#price").value?Number($("#price").value):null,sizes:$("#sizes").value.split(",").map(x=>x.trim()).filter(Boolean),colors:$("#colors").value.split(",").map(x=>x.trim()).filter(Boolean),badge:$("#badge").value.trim(),images:[...existingImages,...uploaded],active:$("#active").checked,customizable:true,sort_order:editing?.sort_order??products.length+1};await KasoliData.saveProduct(value);await load();resetForm();KasoliUI.toast(wasEditing?"Cambios publicados":"Producto publicado")}catch(err){$("#formError").textContent=err.message||"No se pudo guardar. Revisa la conexión e intenta otra vez."}finally{btn.disabled=false;btn.textContent=editing?"Guardar cambios":"Publicar producto"}});
 document.addEventListener("click",e=>{const editBtn=e.target.closest("[data-edit]");if(editBtn)edit(editBtn.dataset.edit);const del=e.target.closest("[data-delete]");if(del){deleteId=del.dataset.delete;const p=products.find(x=>String(x.id)===String(deleteId));$("#deleteDescription").textContent=`“${p.name}” dejará de aparecer en el catálogo y no podrá recuperarse desde este panel.`;$("#deleteDialog").showModal();$("#cancelDelete").focus()}const rf=e.target.closest("[data-remove-file]");if(rf){files.splice(Number(rf.dataset.removeFile),1);renderUploads()}const re=e.target.closest("[data-remove-existing]");if(re){existingImages.splice(Number(re.dataset.removeExisting),1);renderUploads()}});
 $("#confirmDelete").addEventListener("click",async()=>{const btn=$("#confirmDelete");btn.disabled=true;try{await KasoliData.removeProduct(deleteId);$("#deleteDialog").close();await load();KasoliUI.toast("Producto eliminado")}catch(e){$("#deleteDescription").textContent=e.message||"No se pudo eliminar."}finally{btn.disabled=false}});$("#cancelDelete").addEventListener("click",()=>$("#deleteDialog").close());
 $("#newProduct").addEventListener("click",()=>{resetForm();$("#editor").scrollIntoView({behavior:"smooth"});$("#name").focus()});$("#cancelEdit").addEventListener("click",resetForm);$("#closeEditor").addEventListener("click",resetForm);$("#signOut").addEventListener("click",async()=>{await KasoliData.signOut();location.reload()});$("#adminSearch").addEventListener("input",e=>{search=e.target.value;$("#clearAdminSearch").hidden=!search;render()});$("#clearAdminSearch").addEventListener("click",()=>{$("#adminSearch").value="";search="";$("#clearAdminSearch").hidden=true;render();$("#adminSearch").focus()});
})();
