(async function(){
 const $=s=>document.querySelector(s),esc=KasoliUI.escape;let products=[],category="todos",query="",lastFocus=null,order=[];try{order=JSON.parse(localStorage.getItem("kasoli_order_v2")||"[]")}catch{order=[]}
 const categoryNames=Object.fromEntries(KASOLI_CATEGORIES.map(c=>[c.id,c.name]));
 try{products=await KasoliData.listProducts()}catch(e){products=KASOLI_SEED_PRODUCTS;KasoliUI.toast("Mostramos el catálogo disponible mientras recuperamos la conexión.")}
 function card(p){return `<article class="product-card"><button class="product-image-button" type="button" data-open="${esc(p.id)}" aria-label="Ver ${esc(p.name)}"><img src="${esc(p.images?.[0]||"")}" alt="${esc(p.name)}" loading="lazy"><span class="product-badge">${esc(p.badge||categoryNames[p.category]||"KASOLI")}</span></button><div class="product-meta"><div class="product-type"><span>${esc(categoryNames[p.category]||p.category)}</span><span>${esc(p.material||"")}</span></div><h3>${esc(p.name)}</h3><p>${esc(p.description)}</p><div class="card-actions"><span class="price-label">${KasoliUI.money(p.price)}</span><button type="button" data-open="${esc(p.id)}">Ver opciones</button></div></div></article>`}
 function renderFilters(){const wrap=$("#categoryFilters");wrap.innerHTML=KASOLI_CATEGORIES.map(c=>`<button class="filter-chip" type="button" data-category="${c.id}" aria-pressed="${c.id===category}">${c.name}</button>`).join("")}
 function filtered(){const term=query.trim().toLocaleLowerCase("es");return products.filter(p=>(category==="todos"||p.category===category)&&(!term||[p.name,p.description,p.material,p.collection].join(" ").toLocaleLowerCase("es").includes(term)))}
 function render(){const rows=filtered();$("#productGrid").innerHTML=rows.map(card).join("");$("#emptyState").hidden=rows.length>0;$("#resultsLine").textContent=`${rows.length} ${rows.length===1?"producto":"productos"}`;renderFilters()}
 function options(name,values){if(!values?.length)return"";return `<fieldset class="option-group"><legend>${name}</legend><div class="option-list">${values.map((v,i)=>`<label><input type="radio" name="${name}" value="${esc(v)}" ${i===0?"checked":""}><span>${esc(v)}</span></label>`).join("")}</div></fieldset>`}
 function openProduct(id){const p=products.find(x=>String(x.id)===String(id));if(!p)return;lastFocus=document.activeElement;$("#dialogContent").innerHTML=`<div class="dialog-layout"><div class="dialog-media"><img src="${esc(p.images?.[0])}" alt="${esc(p.name)}"></div><div class="dialog-info"><p class="kicker">${esc(p.collection||categoryNames[p.category])}</p><h2 id="dialogTitle">${esc(p.name)}</h2><p>${esc(p.description)}</p><strong>${KasoliUI.money(p.price)}</strong>${options("Talla",p.sizes)}${options("Color o diseño",p.colors)}<div class="qty-row"><span>Cantidad</span><div class="qty-control"><button type="button" data-qty="-1" aria-label="Disminuir cantidad">−</button><output id="qtyOutput">1</output><button type="button" data-qty="1" aria-label="Aumentar cantidad">+</button></div></div><p class="dialog-error" id="dialogError" aria-live="polite"></p><button class="button button-primary" type="button" data-add="${esc(p.id)}">Agregar a mi pedido</button></div></div>`;$("#productDialog").showModal();$(".dialog-close").focus()}
 function add(id){const p=products.find(x=>String(x.id)===String(id));const size=$("input[name='Talla']:checked")?.value||"";const color=$("input[name='Color o diseño']:checked")?.value||"";const qty=Number($("#qtyOutput")?.value||1);const key=[id,size,color].join("|");const old=order.find(x=>x.key===key);if(old)old.qty+=qty;else order.push({key,id:p.id,name:p.name,image:p.images?.[0],size,color,qty});saveOrder();$("#productDialog").close();KasoliUI.toast(`${p.name} se agregó a tu pedido`);openDrawer()}
 function saveOrder(){try{localStorage.setItem("kasoli_order_v2",JSON.stringify(order))}catch{}renderOrder()}
 function renderOrder(){const count=order.reduce((a,x)=>a+x.qty,0);$("#orderCount").textContent=count;$("#orderItems").innerHTML=order.map((x,i)=>`<article class="drawer-item"><img src="${esc(x.image)}" alt=""><div><strong>${esc(x.name)}</strong><small>${x.size?`Talla: ${esc(x.size)} · `:""}${x.color?`${esc(x.color)} · `:""}Cantidad: ${x.qty}</small></div><button type="button" data-remove="${i}">Quitar</button></article>`).join("");$("#orderEmpty").hidden=order.length>0;$("#orderFoot").hidden=!order.length;const advisor=$("input[name='advisor']:checked")?.value||KASOLI_CONFIG.advisors[0].phone;const lines=order.map((x,i)=>`${i+1}. *${x.name}*${x.size?`\n   Talla: ${x.size}`:""}${x.color?`\n   Color/diseño: ${x.color}`:""}\n   Cantidad: ${x.qty}`).join("\n\n");$("#sendOrder").href=`https://wa.me/${advisor}?text=${encodeURIComponent(`Hola KASOLI 👋 Vi el catálogo y quisiera consultar precio y disponibilidad de:\n\n${lines}\n\n¿Me ayudan a confirmar mi pedido?`)}`}
 function openDrawer(){lastFocus=document.activeElement;document.body.classList.add("drawer-open");$("#drawerBackdrop").hidden=false;$("#orderDrawer").classList.add("is-open");$("#orderDrawer").setAttribute("aria-hidden","false");$("#closeDrawer").focus()}
 function closeDrawer(){document.body.classList.remove("drawer-open");$("#drawerBackdrop").hidden=true;$("#orderDrawer").classList.remove("is-open");$("#orderDrawer").setAttribute("aria-hidden","true");lastFocus?.focus()}
 document.addEventListener("click",e=>{const open=e.target.closest("[data-open]");if(open)openProduct(open.dataset.open);const addButton=e.target.closest("[data-add]");if(addButton)add(addButton.dataset.add);const remove=e.target.closest("[data-remove]");if(remove){order.splice(Number(remove.dataset.remove),1);saveOrder()}const chip=e.target.closest("[data-category]");if(chip){category=chip.dataset.category;render()}const qty=e.target.closest("[data-qty]");if(qty){const out=$("#qtyOutput");out.value=Math.max(1,Number(out.value)+Number(qty.dataset.qty));out.textContent=out.value}});
 $("#catalogSearch").addEventListener("input",e=>{query=e.target.value;$("#clearSearch").hidden=!query;render()});$("#clearSearch").addEventListener("click",()=>{$("#catalogSearch").value="";query="";$("#clearSearch").hidden=true;render();$("#catalogSearch").focus()});$("#resetFilters").addEventListener("click",()=>{category="todos";query="";$("#catalogSearch").value="";$("#clearSearch").hidden=true;render()});
 $("#orderTrigger").addEventListener("click",openDrawer);$("#closeDrawer").addEventListener("click",closeDrawer);$("#drawerBackdrop").addEventListener("click",closeDrawer);$("#exploreFromDrawer").addEventListener("click",closeDrawer);$("#productDialog").addEventListener("close",()=>lastFocus?.focus());$("#productDialog").addEventListener("click",e=>{if(e.target===$("#productDialog"))$("#productDialog").close()});$(".dialog-close").addEventListener("click",()=>$("#productDialog").close());document.addEventListener("change",e=>{if(e.target.name==="advisor")renderOrder()});document.addEventListener("keydown",e=>{if(e.key==="Escape"&&$("#orderDrawer").classList.contains("is-open"))closeDrawer();if(e.key==="Tab"&&$("#orderDrawer").classList.contains("is-open")){const focusable=[...$("#orderDrawer").querySelectorAll('button,a,input:not([disabled])')].filter(x=>!x.hidden);const first=focusable[0],last=focusable.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}});
 $("[data-whatsapp='personalize']").href=`https://wa.me/573174070511?text=${encodeURIComponent("Hola KASOLI 👋 Quiero personalizar una camiseta o producto. Tengo una idea y quisiera recibir asesoría.")}`;$("#year").textContent=new Date().getFullYear();render();renderOrder();
})();
