window.KASOLI_SEED_PRODUCTS=[
 {id:"cam-basicas",name:"Camisetas básicas lisas",category:"camisetas",collection:"General",material:"Seda fría o piel de durazno",description:"Camisetas básicas lisas, sin nombre de marca ni estampado. Frescas, cómodas y disponibles en varios colores para usar así o personalizar con tu propio diseño.",images:["/assets/productos/camisetas-basicas.png"],sizes:["S","M","L","XL","XXL"],colors:["Negro","Blanco","Gris","Beige","Vinotinto","Rosa","Coral","Lila","Azul claro","Verde menta","Azul petróleo"],badge:"Sin estampado",price:null,active:true,customizable:true,sort_order:1},
 {id:"cam-seda",name:"Camiseta seda fría personalizada",category:"camisetas",collection:"General y cristiana",material:"Tela seda fría",description:"Suave, ligera, fresca y no se arruga fácilmente. Disponible con cuello redondo o cuello V.",images:["/assets/productos/camisetas-seda-fria.png"],sizes:["S","M","L","XL","XXL"],colors:["Negro","Blanco","Gris","Beige","Vinotinto","Rosa","Coral","Lila","Azul claro","Verde menta","Azul petróleo"],badge:"Personalizable",price:null,active:true,customizable:true,sort_order:2},
 {id:"cam-durazno",name:"Camiseta piel de durazno",category:"camisetas",collection:"General y cristiana",material:"Tela piel de durazno",description:"Tacto suave y aterciopelado, cómoda y premium. Ideal para estampados con excelente definición.",images:["/assets/productos/camisetas-frases.jpg"],sizes:["S","M","L","XL","XXL"],colors:["Blanco","Negro","Según disponibilidad"],badge:"Tacto premium",price:null,active:true,customizable:true,sort_order:3},
 {id:"cam-estampadas",name:"Camisetas estampadas surtidas",category:"camisetas",collection:"General",material:"Consultar tela disponible",description:"Diseños surtidos y estampados para diferentes estilos. Pregunta por las referencias disponibles.",images:["/assets/productos/camisetas-estampadas.jpg"],sizes:["S","M","L","XL","XXL"],colors:["Surtidos"],badge:"Variedad",price:null,active:true,customizable:false,sort_order:4},
 {id:"bol-negro",name:"Bolso negro tejido con detalles",category:"bolsos",collection:"Artesanal",material:"Tejido artesanal",description:"Bolso negro con cuentas de colores y herrajes dorados. Correa combinada para llevar al hombro.",images:["/assets/productos/bolso-negro-correa.jpg","/assets/productos/bolso-negro-detalle.jpg"],sizes:["Mediano"],colors:["Negro"],badge:"Hecho a mano",price:null,active:true,customizable:true,sort_order:5},
 {id:"bol-coleccion",name:"Bolsos tejidos personalizados",category:"bolsos",collection:"Artesanal",material:"Tejido artesanal",description:"Modelos pequeños, medianos y grandes. Personalizamos colores, asas y detalles según el diseño.",images:["/assets/productos/coleccion-bolsos.jpg"],sizes:["Pequeño","Mediano","Grande"],colors:["Personalizable"],badge:"A tu medida",price:null,active:true,customizable:true,sort_order:6},
 {id:"mochila-wayuu",name:"Mochila tejida multicolor",category:"artesanias",collection:"Artesanal",material:"Hilo tejido",description:"Mochila de gran capacidad con patrones llenos de color, correa tejida y borlas decorativas.",images:["/assets/productos/mochila-wayuu-tricolor.jpg"],sizes:["Grande"],colors:["Multicolor"],badge:"Pieza especial",price:null,active:true,customizable:true,sort_order:7}
];
window.KASOLI_CATEGORIES=[{id:"todos",name:"Todo"},{id:"camisetas",name:"Camisetas"},{id:"bolsos",name:"Bolsos"},{id:"artesanias",name:"Artesanías"},{id:"proximamente",name:"Próximamente"}];
